/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface PskBarcodeGenerator {
        "data": any;
        "includeText": boolean;
        "size"?: any;
        "title": string;
        "type": string;
    }
    interface PskBarcodeScanner {
        "data": any;
        "hideDrawing": false;
        "noLogs": false;
        "snapVideo": false;
        "switchCamera": () => Promise<void>;
    }
}
declare global {
    interface HTMLPskBarcodeGeneratorElement extends Components.PskBarcodeGenerator, HTMLStencilElement {
    }
    var HTMLPskBarcodeGeneratorElement: {
        prototype: HTMLPskBarcodeGeneratorElement;
        new (): HTMLPskBarcodeGeneratorElement;
    };
    interface HTMLPskBarcodeScannerElement extends Components.PskBarcodeScanner, HTMLStencilElement {
    }
    var HTMLPskBarcodeScannerElement: {
        prototype: HTMLPskBarcodeScannerElement;
        new (): HTMLPskBarcodeScannerElement;
    };
    interface HTMLElementTagNameMap {
        "psk-barcode-generator": HTMLPskBarcodeGeneratorElement;
        "psk-barcode-scanner": HTMLPskBarcodeScannerElement;
    }
}
declare namespace LocalJSX {
    interface PskBarcodeGenerator {
        "data"?: any;
        "includeText"?: boolean;
        "size"?: any;
        "title"?: string;
        "type"?: string;
    }
    interface PskBarcodeScanner {
        "data"?: any;
        "hideDrawing"?: false;
        "noLogs"?: false;
        "snapVideo"?: false;
    }
    interface IntrinsicElements {
        "psk-barcode-generator": PskBarcodeGenerator;
        "psk-barcode-scanner": PskBarcodeScanner;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "psk-barcode-generator": LocalJSX.PskBarcodeGenerator & JSXBase.HTMLAttributes<HTMLPskBarcodeGeneratorElement>;
            "psk-barcode-scanner": LocalJSX.PskBarcodeScanner & JSXBase.HTMLAttributes<HTMLPskBarcodeScannerElement>;
        }
    }
}
